version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: coursedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: dev

  adminer:
    image: adminer
    ports:
      - "8081:8080"